language: java
sudo: true
#env:
#  - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m"
script:
  - ./gradlew -S -i --max-workers=2 --no-daemon clean check build
jdk:
  - openjdk8
os:
  - linux
cache:
  directories:
    - $HOME/.gradle
